version: '3.8'

services:
  php:
    build:
      context: ./api
    environment:
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      DATABASE_URL: ${DATABASE_URL}
      CORS_ALLOW_ORIGIN: ${CORS_ALLOW_ORIGIN}
    networks:
      - api-net
    depends_on:
      - db
    env_file:
      - .env

  nginx:
    image: nginx:stable
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./api:/var/www/html
    depends_on:
      - php
    networks:
      - api-net

  db:
    image: mariadb:10.6
    environment:
      MARIADB_DATABASE: ${MYSQL_DATABASE}
      MARIADB_USER: ${MYSQL_USER}
      MARIADB_PASSWORD: ${MYSQL_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - api-net
    env_file:
      - .env

volumes:
  db-data:

networks:
  api-net: