version: '3.8'

services:
  backend:
    image: peincolt/api-swgoh:php-apache
    container_name: api_swgoh_backend
    restart: always
    working_dir: /var/www/html
    volumes:
      - ../:/var/www/html
    ports:
      - "8082:80"
    environment:
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      DATABASE_URL: ${DATABASE_URL}
      CORS: ${CORS}
    depends_on:
      - database

  frontend:
    image: peincolt/api-swgoh:nginx
    container_name: api_swgoh_frontend
    restart: always
    volumes:
      - ../:/var/www/html
    ports:
      - "8081:80"
    depends_on:
      - backend

  database:
    image: mariadb:10.5
    container_name: api_swgoh_db
    restart: always
    environment:
      MARIADB_DATABASE: ${MYSQL_DATABASE}
      MARIADB_USER: ${MYSQL_USER}
      MARIADB_PASSWORD: ${MYSQL_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: api_swgoh_phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: database
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - database

volumes:
  dbdata:
