version: '3'
services:
    frontend:
        image: peincolt/api-swgoh:nginx
        restart: always
        volumes:
            - vnginx:/etc/nginx
            - vfrontend:/var/www/html
        ports:
            - 8081:80
        depends_on:
            - backend

    backend:
        image: peincolt/api-swgoh:php-apache
        restart: always
        environment:
            DATABASE_URL: mysql://api-user:JGVbc\02YGBY4hsPKJTN@db:3306/api_guild_swgoh
            APP_ENV: dev
        volumes:
            - vbackend:/var/www/symfony
        ports:
            - 8082:80
        links:
            - "database:db"

    database:
        image: mariadb
        environment:
            MARIADB_DATABASE: api_guild_swgoh
            MARIADB_USER: api-user
            MARIADB_PASSWORD: JGVbc\02YGBY4hsPKJTN
            MARIADB_ROOT_PASSWORD: JGVbc\02YGBY4hsPKJTN
        restart: always
        volumes:
            - vdatabase:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin
        ports:
            - 8080:80
        restart: always
        environment:
            - PMA_ARBITRARY=1

volumes:
    vfrontend:
    vbackend:
    vdatabase:
    vnginx: